/* C2PAddressBookListRow.h generated by valac 0.56.18, the Vala compiler, do not modify */

#ifndef __SRC_VIEW_GTK_C2PADDRESSBOOKLISTROW_H__
#define __SRC_VIEW_GTK_C2PADDRESSBOOKLISTROW_H__

#include <gtk/gtk.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>

G_BEGIN_DECLS

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define C2P_TYPE_ADDRESS_BOOK_LIST_ROW (c2p_address_book_list_row_get_type ())
#define C2P_ADDRESS_BOOK_LIST_ROW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), C2P_TYPE_ADDRESS_BOOK_LIST_ROW, C2PAddressBookListRow))
#define C2P_ADDRESS_BOOK_LIST_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), C2P_TYPE_ADDRESS_BOOK_LIST_ROW, C2PAddressBookListRowClass))
#define C2P_IS_ADDRESS_BOOK_LIST_ROW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), C2P_TYPE_ADDRESS_BOOK_LIST_ROW))
#define C2P_IS_ADDRESS_BOOK_LIST_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), C2P_TYPE_ADDRESS_BOOK_LIST_ROW))
#define C2P_ADDRESS_BOOK_LIST_ROW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), C2P_TYPE_ADDRESS_BOOK_LIST_ROW, C2PAddressBookListRowClass))

typedef struct _C2PAddressBookListRow C2PAddressBookListRow;
typedef struct _C2PAddressBookListRowClass C2PAddressBookListRowClass;
typedef struct _C2PAddressBookListRowPrivate C2PAddressBookListRowPrivate;

struct _C2PAddressBookListRow {
	GtkListBoxRow parent_instance;
	C2PAddressBookListRowPrivate * priv;
};

struct _C2PAddressBookListRowClass {
	GtkListBoxRowClass parent_class;
};

VALA_EXTERN GType c2p_address_book_list_row_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (C2PAddressBookListRow, g_object_unref)
VALA_EXTERN C2PAddressBookListRow* c2p_address_book_list_row_new (void);
VALA_EXTERN C2PAddressBookListRow* c2p_address_book_list_row_construct (GType object_type);
VALA_EXTERN const gchar* c2p_address_book_list_row_get_label (C2PAddressBookListRow* self);
VALA_EXTERN void c2p_address_book_list_row_set_label (C2PAddressBookListRow* self,
                                          const gchar* value);
VALA_EXTERN gint c2p_address_book_list_row_get_num_contacts (C2PAddressBookListRow* self);
VALA_EXTERN void c2p_address_book_list_row_set_num_contacts (C2PAddressBookListRow* self,
                                                 gint value);

G_END_DECLS

#endif
