/* C2PAddressBookListRow.c generated by valac 0.56.18, the Vala compiler
 * generated from C2PAddressBookListRow.vala, do not modify */

/*
 * Copyright 2025 Sergey Bugaev <bugaevc AT gmail DOT com>
 *
 * This software is licensed under the GNU General Public License
 * (version 2.0 or later). See the LICENSE file in this distribution.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define C2P_TYPE_ADDRESS_BOOK_LIST_ROW (c2p_address_book_list_row_get_type ())
#define C2P_ADDRESS_BOOK_LIST_ROW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), C2P_TYPE_ADDRESS_BOOK_LIST_ROW, C2PAddressBookListRow))
#define C2P_ADDRESS_BOOK_LIST_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), C2P_TYPE_ADDRESS_BOOK_LIST_ROW, C2PAddressBookListRowClass))
#define C2P_IS_ADDRESS_BOOK_LIST_ROW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), C2P_TYPE_ADDRESS_BOOK_LIST_ROW))
#define C2P_IS_ADDRESS_BOOK_LIST_ROW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), C2P_TYPE_ADDRESS_BOOK_LIST_ROW))
#define C2P_ADDRESS_BOOK_LIST_ROW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), C2P_TYPE_ADDRESS_BOOK_LIST_ROW, C2PAddressBookListRowClass))

typedef struct _C2PAddressBookListRow C2PAddressBookListRow;
typedef struct _C2PAddressBookListRowClass C2PAddressBookListRowClass;
typedef struct _C2PAddressBookListRowPrivate C2PAddressBookListRowPrivate;
enum  {
	C2P_ADDRESS_BOOK_LIST_ROW_0_PROPERTY,
	C2P_ADDRESS_BOOK_LIST_ROW_LABEL_PROPERTY,
	C2P_ADDRESS_BOOK_LIST_ROW_NUM_CONTACTS_PROPERTY,
	C2P_ADDRESS_BOOK_LIST_ROW_NUM_PROPERTIES
};
static GParamSpec* c2p_address_book_list_row_properties[C2P_ADDRESS_BOOK_LIST_ROW_NUM_PROPERTIES];

struct _C2PAddressBookListRow {
	GtkListBoxRow parent_instance;
	C2PAddressBookListRowPrivate * priv;
};

struct _C2PAddressBookListRowClass {
	GtkListBoxRowClass parent_class;
};

struct _C2PAddressBookListRowPrivate {
	GtkLabel* label_widget;
	gint _num_contacts;
};

static gint C2PAddressBookListRow_private_offset;
static gpointer c2p_address_book_list_row_parent_class = NULL;

VALA_EXTERN GType c2p_address_book_list_row_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (C2PAddressBookListRow, g_object_unref)
VALA_EXTERN C2PAddressBookListRow* c2p_address_book_list_row_new (void);
VALA_EXTERN C2PAddressBookListRow* c2p_address_book_list_row_construct (GType object_type);
VALA_EXTERN const gchar* c2p_address_book_list_row_get_label (C2PAddressBookListRow* self);
VALA_EXTERN void c2p_address_book_list_row_set_label (C2PAddressBookListRow* self,
                                          const gchar* value);
VALA_EXTERN gint c2p_address_book_list_row_get_num_contacts (C2PAddressBookListRow* self);
VALA_EXTERN void c2p_address_book_list_row_set_num_contacts (C2PAddressBookListRow* self,
                                                 gint value);
static void c2p_address_book_list_row_finalize (GObject * obj);
static GType c2p_address_book_list_row_get_type_once (void);
static void _vala_c2p_address_book_list_row_get_property (GObject * object,
                                                   guint property_id,
                                                   GValue * value,
                                                   GParamSpec * pspec);
static void _vala_c2p_address_book_list_row_set_property (GObject * object,
                                                   guint property_id,
                                                   const GValue * value,
                                                   GParamSpec * pspec);

static inline gpointer
c2p_address_book_list_row_get_instance_private (C2PAddressBookListRow* self)
{
	return G_STRUCT_MEMBER_P (self, C2PAddressBookListRow_private_offset);
}

C2PAddressBookListRow*
c2p_address_book_list_row_construct (GType object_type)
{
	C2PAddressBookListRow * self = NULL;
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
	self = (C2PAddressBookListRow*) g_object_new (object_type, NULL);
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
	return self;
#line 108 "C2PAddressBookListRow.c"
}

C2PAddressBookListRow*
c2p_address_book_list_row_new (void)
{
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
	return c2p_address_book_list_row_construct (C2P_TYPE_ADDRESS_BOOK_LIST_ROW);
#line 116 "C2PAddressBookListRow.c"
}

const gchar*
c2p_address_book_list_row_get_label (C2PAddressBookListRow* self)
{
	const gchar* result;
	GtkLabel* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
#line 16 "src/View/GTK/C2PAddressBookListRow.vala"
	g_return_val_if_fail (C2P_IS_ADDRESS_BOOK_LIST_ROW (self), NULL);
#line 16 "src/View/GTK/C2PAddressBookListRow.vala"
	_tmp0_ = self->priv->label_widget;
#line 16 "src/View/GTK/C2PAddressBookListRow.vala"
	_tmp1_ = gtk_label_get_label (_tmp0_);
#line 16 "src/View/GTK/C2PAddressBookListRow.vala"
	_tmp2_ = _tmp1_;
#line 16 "src/View/GTK/C2PAddressBookListRow.vala"
	result = _tmp2_;
#line 16 "src/View/GTK/C2PAddressBookListRow.vala"
	return result;
#line 138 "C2PAddressBookListRow.c"
}

void
c2p_address_book_list_row_set_label (C2PAddressBookListRow* self,
                                     const gchar* value)
{
	GtkLabel* _tmp0_;
#line 17 "src/View/GTK/C2PAddressBookListRow.vala"
	g_return_if_fail (C2P_IS_ADDRESS_BOOK_LIST_ROW (self));
#line 17 "src/View/GTK/C2PAddressBookListRow.vala"
	_tmp0_ = self->priv->label_widget;
#line 17 "src/View/GTK/C2PAddressBookListRow.vala"
	gtk_label_set_label (_tmp0_, value);
#line 17 "src/View/GTK/C2PAddressBookListRow.vala"
	g_object_notify_by_pspec ((GObject *) self, c2p_address_book_list_row_properties[C2P_ADDRESS_BOOK_LIST_ROW_LABEL_PROPERTY]);
#line 154 "C2PAddressBookListRow.c"
}

gint
c2p_address_book_list_row_get_num_contacts (C2PAddressBookListRow* self)
{
	gint result;
#line 20 "src/View/GTK/C2PAddressBookListRow.vala"
	g_return_val_if_fail (C2P_IS_ADDRESS_BOOK_LIST_ROW (self), 0);
#line 20 "src/View/GTK/C2PAddressBookListRow.vala"
	result = self->priv->_num_contacts;
#line 20 "src/View/GTK/C2PAddressBookListRow.vala"
	return result;
#line 167 "C2PAddressBookListRow.c"
}

void
c2p_address_book_list_row_set_num_contacts (C2PAddressBookListRow* self,
                                            gint value)
{
	gint old_value;
#line 20 "src/View/GTK/C2PAddressBookListRow.vala"
	g_return_if_fail (C2P_IS_ADDRESS_BOOK_LIST_ROW (self));
#line 20 "src/View/GTK/C2PAddressBookListRow.vala"
	old_value = c2p_address_book_list_row_get_num_contacts (self);
#line 20 "src/View/GTK/C2PAddressBookListRow.vala"
	if (old_value != value) {
#line 20 "src/View/GTK/C2PAddressBookListRow.vala"
		self->priv->_num_contacts = value;
#line 20 "src/View/GTK/C2PAddressBookListRow.vala"
		g_object_notify_by_pspec ((GObject *) self, c2p_address_book_list_row_properties[C2P_ADDRESS_BOOK_LIST_ROW_NUM_CONTACTS_PROPERTY]);
#line 185 "C2PAddressBookListRow.c"
	}
}

static void
c2p_address_book_list_row_class_init (C2PAddressBookListRowClass * klass,
                                      gpointer klass_data)
{
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
	c2p_address_book_list_row_parent_class = g_type_class_peek_parent (klass);
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
	g_type_class_adjust_private_offset (klass, &C2PAddressBookListRow_private_offset);
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_c2p_address_book_list_row_get_property;
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_c2p_address_book_list_row_set_property;
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
	G_OBJECT_CLASS (klass)->finalize = c2p_address_book_list_row_finalize;
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), C2P_ADDRESS_BOOK_LIST_ROW_LABEL_PROPERTY, c2p_address_book_list_row_properties[C2P_ADDRESS_BOOK_LIST_ROW_LABEL_PROPERTY] = g_param_spec_string ("label", "label", "label", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), C2P_ADDRESS_BOOK_LIST_ROW_NUM_CONTACTS_PROPERTY, c2p_address_book_list_row_properties[C2P_ADDRESS_BOOK_LIST_ROW_NUM_CONTACTS_PROPERTY] = g_param_spec_int ("num-contacts", "num-contacts", "num-contacts", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/de/devbeejohn/c2p/AddressBookListRow.ui");
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "label_widget", FALSE, C2PAddressBookListRow_private_offset + G_STRUCT_OFFSET (C2PAddressBookListRowPrivate, label_widget));
#line 211 "C2PAddressBookListRow.c"
}

static void
c2p_address_book_list_row_instance_init (C2PAddressBookListRow * self,
                                         gpointer klass)
{
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
	self->priv = c2p_address_book_list_row_get_instance_private (self);
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 222 "C2PAddressBookListRow.c"
}

static void
c2p_address_book_list_row_finalize (GObject * obj)
{
	C2PAddressBookListRow * self;
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, C2P_TYPE_ADDRESS_BOOK_LIST_ROW, C2PAddressBookListRow);
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
	G_OBJECT_CLASS (c2p_address_book_list_row_parent_class)->finalize (obj);
#line 233 "C2PAddressBookListRow.c"
}

 G_GNUC_NO_INLINE static GType
c2p_address_book_list_row_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (C2PAddressBookListRowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) c2p_address_book_list_row_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (C2PAddressBookListRow), 0, (GInstanceInitFunc) c2p_address_book_list_row_instance_init, NULL };
	GType c2p_address_book_list_row_type_id;
	c2p_address_book_list_row_type_id = g_type_register_static (gtk_list_box_row_get_type (), "C2PAddressBookListRow", &g_define_type_info, 0);
	C2PAddressBookListRow_private_offset = g_type_add_instance_private (c2p_address_book_list_row_type_id, sizeof (C2PAddressBookListRowPrivate));
	return c2p_address_book_list_row_type_id;
}

GType
c2p_address_book_list_row_get_type (void)
{
	static gsize c2p_address_book_list_row_type_id__once = 0;
	if (g_once_init_enter (&c2p_address_book_list_row_type_id__once)) {
		GType c2p_address_book_list_row_type_id;
		c2p_address_book_list_row_type_id = c2p_address_book_list_row_get_type_once ();
		g_once_init_leave (&c2p_address_book_list_row_type_id__once, c2p_address_book_list_row_type_id);
	}
	return c2p_address_book_list_row_type_id__once;
}

static void
_vala_c2p_address_book_list_row_get_property (GObject * object,
                                              guint property_id,
                                              GValue * value,
                                              GParamSpec * pspec)
{
	C2PAddressBookListRow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, C2P_TYPE_ADDRESS_BOOK_LIST_ROW, C2PAddressBookListRow);
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
	switch (property_id) {
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
		case C2P_ADDRESS_BOOK_LIST_ROW_LABEL_PROPERTY:
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
		g_value_set_string (value, c2p_address_book_list_row_get_label (self));
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
		break;
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
		case C2P_ADDRESS_BOOK_LIST_ROW_NUM_CONTACTS_PROPERTY:
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
		g_value_set_int (value, c2p_address_book_list_row_get_num_contacts (self));
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
		break;
#line 280 "C2PAddressBookListRow.c"
		default:
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
		break;
#line 286 "C2PAddressBookListRow.c"
	}
}

static void
_vala_c2p_address_book_list_row_set_property (GObject * object,
                                              guint property_id,
                                              const GValue * value,
                                              GParamSpec * pspec)
{
	C2PAddressBookListRow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, C2P_TYPE_ADDRESS_BOOK_LIST_ROW, C2PAddressBookListRow);
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
	switch (property_id) {
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
		case C2P_ADDRESS_BOOK_LIST_ROW_LABEL_PROPERTY:
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
		c2p_address_book_list_row_set_label (self, g_value_get_string (value));
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
		break;
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
		case C2P_ADDRESS_BOOK_LIST_ROW_NUM_CONTACTS_PROPERTY:
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
		c2p_address_book_list_row_set_num_contacts (self, g_value_get_int (value));
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
		break;
#line 312 "C2PAddressBookListRow.c"
		default:
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 11 "src/View/GTK/C2PAddressBookListRow.vala"
		break;
#line 318 "C2PAddressBookListRow.c"
	}
}

